name: Check Marlin Version

on:
  schedule:
  - cron: "0 0 * * *"

# on:
#   push:
#     branches:
#       - main

jobs:

  check:
    name: Get Marlin
    runs-on: ubuntu-latest

    steps:

    - name: Checkout self
      uses: actions/checkout@v3

    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        repository: MarlinFirmware/Marlin
        path: Marlin


    - name: detect
      run: |
        ls -la
        cd Marlin

        # Run if the last commit is pushed by cron
        
        GIT_LAST_COMMIT_MSG=$(git log -1 --pretty=%B)

        if echo "$GIT_LAST_COMMIT_MSG" | grep -q "\[cron\]"; then
          echo "Last Commit is [cron]"
          echo "$GIT_LAST_COMMIT_MSG"
        fi
        
        cd ..
        echo "$GIT_LAST_COMMIT_MSG" >> .github/workflows/check_new_version.yml.keeptrack

        cat .github/workflows/check_new_version.yml.keeptrack

        # git config user.name github-actions
        # git config user.email github-actions@github.com
        # git add .
        # git commit -m "New version of Marlin detected: $GIT_LAST_COMMIT_MSG"
        # git push
